from typing import Any, Literal

ExpansionStatus = Literal["implemented", "ready_to_wire", "requires_customer_infra"]


def _module(module_id: str, name: str, owner: str, status: ExpansionStatus, purpose: str, apis: list[str], workflow: list[str], evidence: list[str], gates: list[str]) -> dict[str, Any]:
    return {"id": module_id, "name": name, "owner": owner, "status": status, "purpose": purpose, "api_surface": apis, "workflow": workflow, "evidence": evidence, "readiness_gates": gates}


PRODUCTION_EXPANSION_MODULES = [
    _module("admin_onboarding", "Admin Onboarding Wizard", "platform-admin", "implemented", "Guide a tenant from first login to production-safe CRVM configuration.", ["/api/tenants", "/api/integrations", "/api/policies"], ["Create tenant", "Choose IdP", "Choose secret manager", "Add connector", "Create risk policy"], ["tenant profile", "IdP metadata", "connector profile", "policy record"], ["tenant exists", "RBAC available", "connector dry-run completed"]),
    _module("connector_marketplace", "Connector Marketplace", "integration-engineering", "implemented", "Searchable connector catalog with scopes, setup steps, health checks, and dry-run onboarding.", ["/api/connectors", "/api/connectors/live"], ["Browse", "Review scopes", "Create profile", "Run dry check", "Schedule sync"], ["profile", "health run", "scope list"], ["no raw credentials", "dry-run before live"]),
    _module("data_quality_center", "Data Quality Command Center", "data-platform", "implemented", "Score source freshness, completeness, confidence, duplicates, stale assets, and owner mapping.", ["/api/dashboard", "/api/findings", "/api/assets"], ["Measure freshness", "Find missing fields", "Track duplicates", "Flag stale assets"], ["quality score", "lineage", "owner gaps"], ["freshness scored", "lineage visible"]),
    _module("attack_path_validation_lab", "Attack Path Validation Lab", "exposure-management", "ready_to_wire", "Compare attack graph assumptions against real cloud, IAM, scanner, and network evidence.", ["/api/attack-paths", "/api/asset-graph"], ["Select path", "Review assumptions", "Attach proof", "Recompute confidence"], ["assumptions", "reachability proof", "confidence delta"], ["path exists", "proof attached"]),
    _module("remediation_economics", "Remediation Economics", "security-finance", "implemented", "Calculate risk reduction, engineering effort, SLA cost, exception cost, ROSI, and ROI.", ["/api/reports", "/api/crvm"], ["Estimate effort", "Calculate risk delta", "Compare exception cost", "Publish ROI"], ["ROI report", "risk delta", "effort estimate"], ["risk delta exists", "owner exists"]),
    _module("control_drift_detection", "Control Drift Detection", "sre-security", "ready_to_wire", "Detect removed or weakened virtual patches, IAM denies, segmentation, and cloud guardrails.", ["/api/virtual-patching", "/api/policies"], ["Register control", "Poll state", "Compare expected", "Raise drift alert"], ["expected state", "observed state", "drift alert"], ["owner assigned", "alert route configured"]),
    _module("post_remediation_validation", "Post-Remediation Validation Loop", "security-operations", "implemented", "Trigger validation scans and compare before/after evidence before closure.", ["/api/remediation-actions", "/api/reports"], ["Execute", "Validate", "Compare before/after", "Record residual risk"], ["before state", "validation result", "residual risk"], ["simulation exists", "validation evidence"]),
    _module("customer_policy_builder", "Customer Policy Builder", "governance", "implemented", "No-code policies for auto-approval, freeze windows, exception expiry, evidence gates, and path breakers.", ["/api/policies"], ["Select template", "Set conditions", "Simulate", "Approve", "Audit"], ["policy", "simulation", "decision audit"], ["policy validates", "simulation passes"]),
    _module("plugin_sdk", "Plugin SDK And Example Connector", "developer-platform", "ready_to_wire", "Document extension points for internal connectors and parsers.", ["/api/connectors"], ["Create plugin", "Define parser", "Map fields", "Run contract test"], ["SDK docs", "example connector", "contract test"], ["schema valid", "contract test green"]),
    _module("deployment_hardening_pack", "Deployment Hardening Pack", "devops", "ready_to_wire", "Package Helm, Terraform, production env templates, probes, and runbooks.", ["/api/health", "/api/observability"], ["Render manifests", "Inject secrets", "Run probes", "Validate migrations"], ["Helm values", "Terraform variables", "probe output"], ["non-root image", "health probes"]),
    _module("security_review_pack", "Security Review Pack", "appsec", "ready_to_wire", "Threat model, data-flow diagram, abuse cases, STRIDE, and control mapping.", ["/api/enterprise-readiness"], ["Map data flows", "Review abuse cases", "Map controls", "Export pack"], ["DFD", "STRIDE", "abuse cases"], ["sensitive flows marked", "controls mapped"]),
    _module("executive_narratives", "Executive Narrative Reports", "security-leadership", "implemented", "Board/CISO summaries for risk reduced, paths closed, money saved, and risk accepted.", ["/api/reports", "/api/attack-paths", "/api/crvm"], ["Collect metrics", "Generate narrative", "Attach evidence", "Export"], ["board report", "CISO summary", "path closure"], ["metrics current", "evidence linked"]),
    _module("demo_mode_separation", "Live Demo Mode Switch", "product", "implemented", "Separate demo/sample flows from production logic with clear runtime mode indicators.", ["/api/mock-ingest", "/api/health"], ["Choose mode", "Load demo on request", "Mark records", "Reset demo"], ["mode flag", "demo lineage"], ["demo data marked", "reset available"]),
    _module("e2e_browser_suite", "E2E Browser Test Suite", "quality-engineering", "ready_to_wire", "Browser tests for connector flow, attack path graph, simulation, evidence export, readiness, and CRVM pages.", ["/", "/integrations", "/attack-paths", "/api/crvm"], ["Start app", "Run flow", "Inspect graph", "Check readiness"], ["trace", "screenshots", "test report"], ["critical paths covered", "CI runnable"]),
    _module("data_residency", "Multi-Region And Data Residency Design", "architecture", "requires_customer_infra", "Region-aware tenants, regional evidence storage, and residency policy checks.", ["/api/tenants", "/api/reports"], ["Assign region", "Choose store", "Validate residency", "Audit access"], ["region policy", "storage location", "access audit"], ["region selected", "storage configured"]),
]


def build_production_expansion_model() -> dict[str, Any]:
    implemented = len([item for item in PRODUCTION_EXPANSION_MODULES if item["status"] == "implemented"])
    ready = len([item for item in PRODUCTION_EXPANSION_MODULES if item["status"] == "ready_to_wire"])
    external = len([item for item in PRODUCTION_EXPANSION_MODULES if item["status"] == "requires_customer_infra"])
    return {"summary": {"modules": len(PRODUCTION_EXPANSION_MODULES), "implemented": implemented, "ready_to_wire": ready, "requires_customer_infra": external, "production_score": round(((implemented + ready * 0.7) / len(PRODUCTION_EXPANSION_MODULES)) * 100)}, "modules": PRODUCTION_EXPANSION_MODULES}
